### ISSUE TITLE
frcKrawler crashes during import of events

### ISSUE THREAD

**Issue by warlord500** [frc2052/FRC-Krawler#12]
we are team 2550 trying to use your app to for our scouting but when ever we try importing the event data for any of the years the app crashes. my guess is the server you are importing the data is from 
down. do you have any suggestions? we are using the latest version you put on the google play.

**Comment by Adam8234** [comment]
It could possibly be a Android version specific issue. **What version of Android are you running?** 

We test on 5.0+ devices. I just tried importing several events on my phone running Android 6.0 and it worked fine. When you export can you report the issue so I can see that log. 

**Can you also be more descriptive so I can try to replicate the issue?**

Thanks!

**Comment by warlord500** [comment]
turns out our wifi connection was too slow during the import. the app would crash when the wifi wasn't working.  we managed to figure out the issue though. 
thank you for the quick response though

**Comment by Adam8234** [comment]
That would do it! :+1:  No problem
