### ISSUE TITLE
Missing Imports

### ISSUE THREAD

**Issue by Bschmitz99** [frc2052/FRC-Krawler#14]
I just forked the project and loaded it on Android Studio and I cannot build the project because there are missing imports.

com.team2052.frckrawler.R
com.team2052.frckrawler.di.DaggerFragmentComponent

Between these two missing files, over 35 others have errors and will not build.

**Comment by Adam8234** [comment]
These classes are compiled during build time. When the app is built, annotation processors and the Android build system generated these files. If you get an error like this, it usually tells me there are different problems. Check the full log and see if it gives any additional info. Thanks!

If it happens to be on our end I'll have that fixed or have a solution for anyone that wants to contribute!

**Comment by Bschmitz99** [comment]
That is what I thought was supposed to happen but it will not even start compiling with the errors. I will go through the logs in a little bit to see what is going on.

**Comment by Bschmitz99** [comment]
That is what I thought was supposed to happen but it will not even start compiling with the errors. I will go through the logs in a little bit to see what is going on.

**Comment by Bschmitz99** [comment]
I looked at the logs and it is stopping before it is even starting to compile because it is missing the google-services.json file. I am assuming I just need to generate one under my own account?

**Comment by Adam8234** [comment]
Correct! As the google-services.json is under my personal account at the moment for the play store releases, I don't want people to misuse it, so I keep it private. I will see if we can alleviate this in the future.

**Comment by Bschmitz99** [comment]
So I generated it with the app name FRC-Krawler and a package name of com.team2052.frckrawler and added it to my folders in both the main app directory and the debug folder and am now getting this error:

Error:Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.team2052.frckrawler.development'

What is going on? And I apologize for not knowing a lot about this, but I usually program iOS apps and have very little experience with Android Studio or the google-services system

**Comment by Bschmitz99** [comment]
Never mind, it tuns out I don't know how to spell frc. I must have typed fcrkrawler instead of frckrawler into the website to generate the google-services.json file. I have achieved a successful gradle build
