### ISSUE TITLE
No matching client found for package name 'com.team2052.frckrawler.development'

### ISSUE THREAD

**Issue by tytremblay** [frc2052/FRC-Krawler#17]
I'm trying to run Krawler for the first time in emulation and running into this error.  I've set up FireBase and added the google-services.json file to FRC-Krawler > app.

`Error:Execution failed for task ':app:processDebugGoogleServices'. > No matching client found for package name 'com.team2052.frckrawler.development'`

**Comment by Adam8234** [comment]
FRC Krawler's debug build has a different package names (.development suffix). Therefore, you need to have a second google-services.json file in the debug src folder. Hope this helps!

![screenshot from 2016-12-16 15-37-43](https://cloud.githubusercontent.com/assets/5498618/21279484/045fdfe2-c3a6-11e6-996b-2bd7c95395f6.png)

**Comment by tytremblay** [comment]
Added the file in that location.  no luck.
![image](https://cloud.githubusercontent.com/assets/6652493/21279716/ac7feb46-c3af-11e6-9fb4-72553504fdf5.png)

**Comment by tytremblay** [comment]
Solved the issue by renaming `package_name` in the file under the debug folder.  
```
"android_client_info": {
          "package_name": "com.team2052.frckrawler.development"
        }
```

**Comment by Adam8234** [comment]
Good! Under Firebase I'd suggest adding adding another app under your project with the ".development" prefix. I guess if Firebase doesn't complain that's all good! :+1:
