### ISSUE TITLE
Application for desktop computer?

### ISSUE THREAD

**Issue by Bschmitz99** [frc2052/FRC-Krawler#19]
Hi, I am from team 2518 and I am wondering if an application can be made that runs on windows computers that connects to the Bluetooth tablets/phones as a server device and all the devices can connect to that to sync instead of another phone/tablet. That would make it a lot easier, where you could just walk into your pit and sync. Bluetooth can really drain the batteries of our phones and tablets really fast as we do not have the funding to afford new devices with the updated hardware that is more power efficient. It could be a simple java jar program I would assume, and seeming how android pretty much is Java, that should not be too difficult right?

**Comment by Adam8234** [comment]
We currently have no motivation to make a Windows application or a cross platform Jar. As Android is very platform specific and there's no 3rd party libraries for cross platform communication with bluetooth. Instead, I'll give you some suggestions that might alleviate your problem...

1. Bring a battery charger that keeps the server tablet charged (this might work for you the best) or bring a DC to AC converter and use an FRC Battery to keep your devices charged
2. Only sync twice a day, turn off screens when needed, keep server powered off and only have powered on when syncing.

Doing 1 and/or 2 will extremely help you guys scout all day. If you have a Chromebook, I would use it as a server. Those things get amazing battery life!
