### ISSUE TITLE
Recent update 

### ISSUE THREAD

**Issue by Team319** [frc2052/FRC-Krawler#26]
Recent update now crashes. we are able to import an event, create a game. But when we add a match metric we get the following error. "Unfortunately, FRC Krawler has stopped". filled out the error log.
Joe Derrick
BigBadBob319@gmail.com

**Comment by Adam8234** [comment]
What device(s) is it crashing like this? What version of Android are they running?

**Comment by Adam8234** [comment]
Looking into this. It looks like you guys are running KitKat. I recently fixed issues similar to this. Expect that the next version will fix this issue. I'll close this issue once it's been confirmed it has been resolved.

**Comment by Team319** [comment]
thanks Adam.

**Comment by Adam8234** [comment]
I just uploaded 3.2.2 to the Google Play Store and the Github Release page. It should fix your issues. Confirm with me as soon as possible.

**Comment by Team319** [comment]
I just updated the app, was able to create metrics on server, use scout
mode on a different device and sync data from that device to the server. So
it seems as if the problem is resolved. Thank you.

Joe Derrick

**Comment by Adam8234** [comment]
Awesome!:tada:
