### ISSUE TITLE
Version 3.3.0 Disabled Manual Event Entry

### ISSUE THREAD

**Issue by TheGreatKetchup** [frc2052/FRC-Krawler#33]
Matt from Team 2537, Columbia Maryland

After updating all of our phones to 3.3.0, it appears to be impossible to add teams to manually created competitions. When a manual event is created, there is no longer a prompt to enter team names, making the event basically useless.

**Comment by Adam8234** [comment]
I'll get a fix out soon. Thanks for the heads up!

**Comment by Adam8234** [comment]
Fixed - 90825a34d56e409628fde285433f9c0c034a9c65
