### ISSUE TITLE
Spike 293 power up problem

### ISSUE THREAD

**Issue by arensouthall** [frc2052/FRC-Krawler#34]
Hello,
Our high school robotics team is having problems with the FRC Krawler app. when we try to use the scouting function on the app, it sets to the 2016-2017 season game. Is there a way to update the game to the 2017-2018 version? It would be a great help to the team if you could help me fix this.
Sincerely,
A team 293 member

**Comment by Adam8234** [comment]
The 2018 compatible version was released the 21st of Jan, a new version with some bug fixes will be released soon.
