### ISSUE TITLE
Issues with raw data export

### ISSUE THREAD

**Issue by Charlieglider** [frc2052/FRC-Krawler#36]
We have been setting up FRC Krawler with all our params, and have been testing some exporting. We are able to export summaries but when exporting raw data the folder shows up blank. When we restart the android device we can see the raw exports in the folder but they are all blank.
 
Can you please help with this?
Thanks

**Comment by Adam8234** [comment]
What version of the app are you running? You can check app info.
What device model number is having the issue? (Settings -> About device -> Device Model)
What version of Android are you running? (Settings -> About device -> Android version)

**Comment by Charlieglider** [comment]
I have solved the issue, but thank you for helping.

It seems that I was getting this error because I was leaving the Chooser parameters blank. I did this in order to make titles for Teleop and Auto. But by leaving them blank I was not able to export raw data.

After inputting a value into the parameters for the Chooser the issue is solved.

**Comment by Adam8234** [comment]
Good to know. This is interesting. Thanks for letting me know what was causing your issue. I will probably have a fix out for that soon if it isn't fixed on 3.3.2. Other people have been having that issue this year it seems. Thanks for your help!
