### ISSUE TITLE
Unable to export to local storage

### ISSUE THREAD

**Issue by Azathoth2k** [frc2052/FRC-Krawler#38]
I am testing v3.3.1 on a Samsung Tab 10.1 running Andriod 5.0.2 and when exporting, I only have the option to export to Save to Drive (google drive), Email or Gmail.  The local storage and SD cards do not appear as options.  I checked the app permissions and it has permissions to read/write to the SD card.

**Comment by Adam8234** [comment]
The export files should be on the local storage if you open a file explorer or plug the device into your computer you should see a folder for FRC Krawler on the device. The dialog that pops up is for when 2052 puts it directly on Google Drive or email it to one of the strategists, but the file is still saved locally. Let know if that helps!
