### ISSUE TITLE
greenDAO generator does not exist

### ISSUE THREAD

**Issue by SlippStream** [frc2052/FRC-Krawler#41]
My team has been poking around in the code, and making changes so that it fits the way we scout better. When we try to build the app, however, we get errors all stemming from "error: package org.greenrobot.greendao.generator does not exist." We have not made any changes to anything relating to greendao, but I can look into the changes we made to help fix this.

**Comment by bherbst** [comment]
Sorry to hear that you are having issues building!

Running `./gradlew assembleDebug` is still working for me.  Can you confirm a few things for me?

 1. What command are you running to build the app?
 1. What is the full output you get when trying to build?
 1. Is your computer connected to the internet? Is it behind a proxy or firewall of any sort?

**Comment by bherbst** [comment]
I am closing this issue because we haven't heard back in quite a while. If you are still running into this issue, feel free to open a new issue with more information!
