### ISSUE TITLE
Changing the server

### ISSUE THREAD

**Issue by Azathoth2k** [frc2052/FRC-Krawler#42]
We played around with FRC Krawler in the off season and a couple of students sync their device with a tablet we will not be using going forward. It doesn't appear there is a way to get the application to change the server it wants to sync from. We tried unpairing the device and uninstalling the app but it always wants to sync with the old device.  Is there a file on the device OS that needs to be deleted?

Thanks,

Keith

**Comment by Azathoth2k** [comment]
The old device was not on was miles away but the app would not allow for selecting another device to sync to.  We connected the phone to a PC and tried to locate the FRC Krawler data but was not able to find it. 
Thanks,
Keith


-----Original Message-----

**Comment by bherbst** [comment]
@Azathoth2k I just tried to go through the process and I'm seeing the same thing, so it looks like we have a bug to fix.

In the meantime the only option would be to clear the app's data on the scouting device.

**Comment by bherbst** [comment]
Version 3.3.4 (rolling out now) supports this!
