### ISSUE TITLE
Export all data to excel, match by match

### ISSUE THREAD

**Issue by Adam8234** [frc2052/FRC-Krawler#5]
Export all data to excel, match by match. No averages. Sorted by team number and match.

**Comment by warlord500** [comment]
team 2550, has had the same problem.  I wasnt the actually looking at the data. but I quote "
all the data was put into a single cell"

**Comment by Adam8234** [comment]
Added in release https://github.com/frc2052/FRC-Krawler/releases/tag/3.1.0-pre1
