### ISSUE TITLE
Unable to use the app

### ISSUE THREAD

**Issue by Antonios-P** [frc2052/FRC-Krawler#53]
```Issue Description:``` I have paired the devices to Bluetooth. I'm not sure that the devices are even connected to each other, because ```Connected``` disappears after a split second. When I enter the app, it says that the server is off. I can't setup the server bottom-line. I also would like to know whether  there are any pre-made metrics for 2020. 

```Steps to Reproduce```: Get two android devices (Android version irrelevant), and pair them with Bluetooth. Launch FRC Krawler and go through normal first-time setup. Then, watch as the server is off and you can't do anything.

Thanks for all your time and help on this matter.

**Comment by bherbst** [comment]
Thanks for reaching out!

Can you confirm the following for me:

* Under the "games" section in the hamburger menu you have at least one game set up
* If you click into that game and go to the "events" tab you have at least one event set up

If you could also provide a screenshot of what you are seeing, that would help!

**Comment by Antonios-P** [comment]
No games were found and hence, no events. Below is a video of what I am facing.


https://drive.google.com/a/isd535.org/file/d/14cm_-7slvg0rPvMi6yLnlENNakFo8hkO/view?usp=drivesdk

**Comment by Antonios-P** [comment]
No games were found and hence, no events. Below is a video of the problem I'm facing.

https://drive.google.com/file/d/10GO9VKVhT4y6zx-wzpyNOWpd5l1XiQ8W/view?usp=drivesdk

**Comment by bherbst** [comment]
Yep, that looks to be the problem! Before starting the server you need to set up a game and at least one event. You can click the yellow circular "+" button on the lower right of the games screen to create a game, then go into that game and add an event.

**Comment by Antonios-P** [comment]
Thanks. That sounds promising! I'll try that. Are there any premade metrics for 2020 Infinite Recharge?

**Comment by bherbst** [comment]
Unfortunately not yet - we are still finalizing our metrics.

**Comment by Antonios-P** [comment]
I can't add teams in the event. Is that normal?

**Comment by bherbst** [comment]
I assume you are going into the game, then into the event, then clicking the "teams attending" tab, then clicking the "+" button in the bottom right?

If so, what happens when you do that?

**Comment by Antonios-P** [comment]
I really can't do anything within the event. It seems like it's adding the teams, but it does nothing after the adding team screen disappears.

**Comment by bherbst** [comment]
Would you be able to take another video?

**Comment by Antonios-P** [comment]
It works. Turns out you need to have internet to add teams. Lol. My fault.

**Comment by bherbst** [comment]
Glad you got it working!

**Comment by Antonios-P** [comment]
Can you delete some scouting entries? I did them as a test and don't want them anymore.

**Comment by bherbst** [comment]
Not at the moment, but you could just delete the event and re-create it if you want to just clear all the entries from the event.

**Comment by Antonios-P** [comment]
Ok thanks
